export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TIMESHEET_LOADING = 'TIMESHEET_LOADING';
export const GET_TIMESHEETS = 'GET_TIMESHEETS';
export const ADD_TIMESHEET = 'ADD_TIMESHEET';
export const ADD_TASK = 'ADD_TASK';
